
//Get a hello
GET http://localhost:8080/
Accept: text/plain

###

//Get city information by id
GET http://localhost:8080/city/606
Accept: application/json

###

//Create new city using port 8080
POST http://localhost:8080/create
Content-Type: application/json

{
  "id" : "4942",
  "name": "Кострома",
  "region": "Костромская область",
  "district": "Центральный",
  "population": 277000,
  "foundation": 1152
}

###

//Create new city using port 8081
POST http://localhost:8081/create
Content-Type: application/json

{
  "id" : "4932",
  "name": "Иваново",
  "region": "Ивановская область",
  "district": "Центральный",
  "population": 45,
  "foundation": 1871
}

###

//Change city population
PUT http://localhost:8080/update/4942
Content-Type: application/json

{"new population": 277022}

###

//Change city population
PUT http://localhost:8080/update/4932
Content-Type: application/json

{"new population": 399983}

###

//Get all cities in the region
GET http://localhost:8081/region/Костромская область
Accept: application/json

###

//Get all cities in the region
GET http://localhost:8080/region/Татарстан
Accept: application/json

###

//Get all cities in the district
GET http://localhost:8080/district/Приволжский
Accept: application/json

###

//Get all cities over specified population range
GET http://localhost:8080/population/800000-1000000
Accept: application/json

###

//Get all cities over specified foundation range
GET http://localhost:8080/foundation/1800
Accept: application/json

###

//Delete city by id
DELETE http://localhost:8080/
Content-Type: application/json

{"target_id": "4942"}